import '../all_view_food_one_screen/widgets/dish5_item_widget.dart';import '../all_view_food_one_screen/widgets/fiftyone_item_widget.dart';import 'models/all_view_food_one_model.dart';import 'models/dish5_item_model.dart';import 'models/fiftyone_item_model.dart';import 'package:arest/core/app_export.dart';import 'package:arest/presentation/dashboard_one_page/dashboard_one_page.dart';import 'package:arest/widgets/app_bar/appbar_leading_image.dart';import 'package:arest/widgets/app_bar/appbar_title_image.dart';import 'package:arest/widgets/app_bar/appbar_trailing_circleimage.dart';import 'package:arest/widgets/app_bar/custom_app_bar.dart';import 'package:arest/widgets/custom_bottom_bar.dart';import 'package:arest/widgets/custom_icon_button.dart';import 'package:flutter/material.dart';import 'provider/all_view_food_one_provider.dart';class AllViewFoodOneScreen extends StatefulWidget {const AllViewFoodOneScreen({Key? key}) : super(key: key);

@override AllViewFoodOneScreenState createState() =>  AllViewFoodOneScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => AllViewFoodOneProvider(), child: AllViewFoodOneScreen()); } 
 }

// ignore_for_file: must_be_immutable
class AllViewFoodOneScreenState extends State<AllViewFoodOneScreen> {GlobalKey<NavigatorState> navigatorKey = GlobalKey();

@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 27.v), child: Column(children: [_buildFrameEight(context), SizedBox(height: 16.v), _buildFrameNine(context), SizedBox(height: 37.v), _buildFrameTen(context), SizedBox(height: 11.v), _buildFiftyOne(context)])), bottomNavigationBar: _buildBottomBar(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 51.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgMegaphone, margin: EdgeInsets.only(left: 33.h, top: 63.v, bottom: 19.v)), centerTitle: true, title: Padding(padding: EdgeInsets.only(top: 56.v, bottom: 13.v), child: Row(children: [AppbarTitleImage(imagePath: ImageConstant.imgLock, margin: EdgeInsets.only(bottom: 1.v)), Padding(padding: EdgeInsets.only(left: 5.h), child: RichText(text: TextSpan(children: [TextSpan(text: "lbl_ar".tr, style: CustomTextStyles.titleLargeff009944), TextSpan(text: "lbl_estro".tr, style: CustomTextStyles.titleLargeff004422)]), textAlign: TextAlign.left))])), actions: [AppbarTrailingCircleimage(imagePath: ImageConstant.imgEllipse4, margin: EdgeInsets.fromLTRB(34.h, 56.v, 34.h, 12.v), onTap: () {onTapCircleImage(context);})], styleType: Style.bgShadow); } 
/// Section Widget
Widget _buildFrameEight(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 38.h, right: 31.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(width: 152.h, child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(top: 4.v, bottom: 3.v), child: Text("lbl_best_offers".tr, style: CustomTextStyles.titleLargeManropeBluegray800)), Padding(padding: EdgeInsets.only(left: 8.h), child: CustomIconButton(height: 36.adaptSize, width: 36.adaptSize, padding: EdgeInsets.all(10.h), decoration: IconButtonStyleHelper.outlineDeepOrangeC, child: CustomImageView(imagePath: ImageConstant.imgFrame5)))])), Spacer(), Padding(padding: EdgeInsets.symmetric(vertical: 9.v), child: Text("lbl_see_all".tr, style: CustomTextStyles.bodySmallNunitoTeal900)), CustomImageView(imagePath: ImageConstant.imgArrowRightTeal900, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(left: 4.h, top: 10.v, bottom: 10.v))])); } 
/// Section Widget
Widget _buildFrameNine(BuildContext context) { return GestureDetector(onTap: () {onTapFrameNine(context);}, child: Padding(padding: EdgeInsets.only(left: 16.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 287.v, width: 168.h, child: Stack(alignment: Alignment.centerRight, children: [CustomImageView(imagePath: ImageConstant.imgPngegg1, height: 167.v, width: 168.h, alignment: Alignment.topCenter), Align(alignment: Alignment.centerRight, child: Container(height: 282.v, width: 142.h, margin: EdgeInsets.only(right: 5.h), child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.bottomCenter, child: Container(margin: EdgeInsets.symmetric(horizontal: 12.h), padding: EdgeInsets.symmetric(horizontal: 19.h, vertical: 20.v), decoration: AppDecoration.outlinePrimary.copyWith(borderRadius: BorderRadiusStyle.circleBorder16), child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 65.v), Text("lbl_food_1".tr, style: CustomTextStyles.titleMediumBlack90002), SizedBox(height: 13.v), Text("lbl_some_details".tr, style: CustomTextStyles.labelLargeManropeBluegray300), SizedBox(height: 9.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 3.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(bottom: 12.v), child: Text("lbl_rs".tr, style: CustomTextStyles.labelMediumManropeOnError)), Padding(padding: EdgeInsets.only(left: 4.h), child: Text("lbl_310".tr, style: CustomTextStyles.titleMediumPrimary))])))]))), Align(alignment: Alignment.topCenter, child: Container(height: 142.adaptSize, width: 142.adaptSize, decoration: BoxDecoration(color: appTheme.whiteA70002, borderRadius: BorderRadius.circular(71.h))))])))])), Expanded(child: SizedBox(height: 287.v, child: Consumer<AllViewFoodOneProvider>(builder: (context, provider, child) {return ListView.separated(padding: EdgeInsets.only(left: 16.h, top: 26.v, bottom: 26.v), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 16.h);}, itemCount: provider.allViewFoodOneModelObj.dish5ItemList.length, itemBuilder: (context, index) {Dish5ItemModel model = provider.allViewFoodOneModelObj.dish5ItemList[index]; return Dish5ItemWidget(model);});})))]))); } 
/// Section Widget
Widget _buildFrameTen(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 38.h, right: 31.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.end, children: [Text("msg_popular_food_nearby".tr, style: CustomTextStyles.titleLargeManropeBluegray800), Spacer(), Padding(padding: EdgeInsets.only(top: 7.v, bottom: 3.v), child: Text("lbl_see_all".tr, style: CustomTextStyles.bodySmallNunitoTeal900)), CustomImageView(imagePath: ImageConstant.imgArrowRightTeal900, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(left: 4.h, top: 7.v, bottom: 4.v))])); } 
/// Section Widget
Widget _buildFiftyOne(BuildContext context) { return SizedBox(height: 109.v, child: Consumer<AllViewFoodOneProvider>(builder: (context, provider, child) {return ListView.separated(scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 1.h);}, itemCount: provider.allViewFoodOneModelObj.fiftyoneItemList.length, itemBuilder: (context, index) {FiftyoneItemModel model = provider.allViewFoodOneModelObj.fiftyoneItemList[index]; return FiftyoneItemWidget(model);});})); } 
/// Section Widget
Widget _buildBottomBar(BuildContext context) { return CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Home: return "/"; case BottomBarEnum.Search: return "/"; case BottomBarEnum.Cart: return AppRoutes.dashboardOnePage; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(BuildContext context, String currentRoute, ) { switch (currentRoute) {case AppRoutes.dashboardOnePage: return DashboardOnePage.builder(context); default: return DefaultWidget();} } 
/// Navigates to the profileScreen when the action is triggered.
onTapCircleImage(BuildContext context) { NavigatorService.pushNamed(AppRoutes.profileScreen, ); } 
/// Navigates to the foodOrderFoodDetailsScreen when the action is triggered.
onTapFrameNine(BuildContext context) { NavigatorService.pushNamed(AppRoutes.foodOrderFoodDetailsScreen, ); } 
 }
