import 'models/table_reservation_successful_model.dart';import 'package:arest/core/app_export.dart';import 'package:arest/widgets/app_bar/appbar_leading_image.dart';import 'package:arest/widgets/app_bar/appbar_title_image.dart';import 'package:arest/widgets/app_bar/appbar_trailing_circleimage.dart';import 'package:arest/widgets/app_bar/custom_app_bar.dart';import 'package:arest/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'provider/table_reservation_successful_provider.dart';class TableReservationSuccessfulScreen extends StatefulWidget {const TableReservationSuccessfulScreen({Key? key}) : super(key: key);

@override TableReservationSuccessfulScreenState createState() =>  TableReservationSuccessfulScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => TableReservationSuccessfulProvider(), child: TableReservationSuccessfulScreen()); } 
 }
class TableReservationSuccessfulScreenState extends State<TableReservationSuccessfulScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: appTheme.whiteA700, body: SizedBox(height: SizeUtils.height, width: double.maxFinite, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgPattern, height: 844.v, width: 390.h, alignment: Alignment.center), Align(alignment: Alignment.center, child: Column(mainAxisSize: MainAxisSize.min, children: [_buildAppBar(context), SizedBox(height: 99.v), Expanded(child: SingleChildScrollView(child: Container(height: 607.v, width: double.maxFinite, margin: EdgeInsets.only(bottom: 37.v), padding: EdgeInsets.symmetric(horizontal: 32.h), child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.bottomLeft, child: Text("lbl_book_now".tr, style: CustomTextStyles.labelLargePoppinsWhiteA70002)), Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.symmetric(horizontal: 27.h), child: Column(mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgUndrawOrderCo, height: 167.v, width: 220.h, alignment: Alignment.centerLeft, margin: EdgeInsets.only(left: 21.h)), SizedBox(height: 38.v), SizedBox(width: 271.h, child: Text("msg_your_table_was_reserved".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.headlineSmallPrimary)), SizedBox(height: 7.v), Container(width: 256.h, margin: EdgeInsets.only(left: 7.h, right: 8.h), child: Text("msg_please_respect_our".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.bodySmallGray60001))]))), CustomElevatedButton(width: 312.h, text: "lbl_order_food".tr, margin: EdgeInsets.only(bottom: 8.v), onPressed: () {onTapOrderFood(context);}, alignment: Alignment.bottomCenter)]))))]))])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 51.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgMegaphone, margin: EdgeInsets.only(left: 33.h, top: 63.v, bottom: 19.v)), centerTitle: true, title: Padding(padding: EdgeInsets.only(top: 56.v, bottom: 13.v), child: Row(children: [AppbarTitleImage(imagePath: ImageConstant.imgLock, margin: EdgeInsets.only(bottom: 1.v)), Padding(padding: EdgeInsets.only(left: 5.h), child: RichText(text: TextSpan(children: [TextSpan(text: "lbl_ar".tr, style: CustomTextStyles.titleLargeff009944), TextSpan(text: "lbl_estro".tr, style: CustomTextStyles.titleLargeff004422)]), textAlign: TextAlign.left))])), actions: [AppbarTrailingCircleimage(imagePath: ImageConstant.imgEllipse4, margin: EdgeInsets.fromLTRB(34.h, 56.v, 34.h, 12.v), onTap: () {onTapCircleImage(context);})], styleType: Style.bgShadow); } 
/// Navigates to the profileScreen when the action is triggered.
onTapCircleImage(BuildContext context) { NavigatorService.pushNamed(AppRoutes.profileScreen, ); } 
/// Navigates to the dashboardScreen when the action is triggered.
onTapOrderFood(BuildContext context) { NavigatorService.pushNamed(AppRoutes.dashboardScreen, ); } 
 }
